SELECT * FROM models;
SELECT * FROM models WHERE NOT status ='Destroyed';
SELECT * FROM models WHERE NOT mark ='Mark-3' AND NOT mark ='Mark-4' AND NOT mark ='Mark-5';
SELECT * FROM models ORDER BY mark DESC;
SELECT * FROM models WHERE launch = (SELECT MIN(launch) FROM models);
SELECT * FROM models WHERE kaijuKill = (SELECT MAX(kaijuKill) FROM models);
SELECT * FROM models WHERE kaijuKill = (SELECT MIN(kaijuKill) FROM models);
SELECT AVG(weight) AS mark FROM models;
UPDATE models SET kaijuKill = kaijuKill+1 WHERE NOT status ='Destroyed';
DELETE FROM models WHERE status ='Destroyed';
